version: '3'

services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./dist/wep-app:/usr/share/nginx/html:rw
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf/:rw
    restart: "always"
    ports:
      - "80:80"
    networks:
      - my-network
  puc-minas-backend:
    image: caetanogs/puc-minas-backend
    environment:
      - DATABASE_URL=file:./dev.db
      - TOKEN_SECRET=test
    ports:
      - "3000:3000"
    restart: "always"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
